# netlify.toml — for Meteor Impact Simulator 🚀
[build]
  command = "npm run build"
  publish = "dist"

# Optional: environment variables (if you ever need them)
#[build.environment]
#  VITE_API_URL = "https://your-api-endpoint.com"

# Redirect all routes to index.html (important for React apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
